# Generated by Django 2.2.5 on 2019-09-20 13:18

from django.db import migrations, models
import django.db.models.deletion
import garden.models.flower


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=garden.models.flower.Flower.get_image_path)),
                ('info', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.Category')),
            ],
            options={
                'verbose_name': 'The Garden',
                'verbose_name_plural': 'The Garden',
            },
        ),
    ]
